services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: pdb
  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 9090:8080
    volumes:
      - ./app-realm.json:/opt/keycloak/data/import/app-realm.json
    command:
      - start-dev
      - --import-realm
  mongo:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    #   MONGO_INITDB_DATABASE: languages
    ports:
      - 27017:27017
    # volumes:
    #   - ./init-mongo.js:/docker-entrypoint-initdb.d/db.js

  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image:
        mariakoren/project-backend:latest
    ports:
      - 5000:5000
    depends_on:
      - mongo

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image:
        mariakoren/project-frontend:latest
    ports:
      - 8080:80
    depends_on:
      - keycloak
      - mongo
      - backend

  nginx:
    image: nginx:latest
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    depends_on:
      - frontend


# /opt/keycloak/bin/kc.sh export --realm=app --dir=/opt/keycloak/data/export --users=realm_file
# docker cp project-keycloak-1:/opt/keycloak/data/export/app-realm.json /mnt/c/Users/maria/Desktop/projekt---technologie-chmurowe-mariakoren/project/app-realm.json


# docker build -t mariakoren/project-backend:latest .
# docker push mariakoren/project-backend:latest

# docker build -t mariakoren/project-frontend:latest .
# docker push mariakoren/project-frontend:latest
